// Dataset de canciones conocidas en España. g:true = grupo/banda, g:false = solista.
// y = año de publicación. ~10% anteriores a 1980, ~90% entre 1980 y 2026.

const SONGS = [

// ============ CLÁSICOS ANTERIORES A 1980 (~10%) ============
{t:"Fly Me to the Moon",a:"Frank Sinatra",y:1954,g:false},
{t:"What a Wonderful World",a:"Louis Armstrong",y:1959,g:false},
{t:"La Bamba",a:"Ritchie Valens",y:1958,g:false},
{t:"Hound Dog",a:"Elvis Presley",y:1956,g:false},
{t:"Jailhouse Rock",a:"Elvis Presley",y:1957,g:false},
{t:"I Want to Hold Your Hand",a:"The Beatles",y:1963,g:true},
{t:"Yesterday",a:"The Beatles",y:1965,g:true},
{t:"Hey Jude",a:"The Beatles",y:1968,g:true},
{t:"Let It Be",a:"The Beatles",y:1970,g:true},
{t:"(I Can't Get No) Satisfaction",a:"The Rolling Stones",y:1965,g:true},
{t:"House of the Rising Sun",a:"The Animals",y:1964,g:true},
{t:"My Generation",a:"The Who",y:1965,g:true},
{t:"Respect",a:"Aretha Franklin",y:1967,g:false},
{t:"Stand By Me",a:"Ben E. King",y:1961,g:false},
{t:"I Heard It Through the Grapevine",a:"Marvin Gaye",y:1968,g:false},
{t:"Bohemian Rhapsody",a:"Queen",y:1975,g:true},
{t:"Stairway to Heaven",a:"Led Zeppelin",y:1971,g:true},
{t:"Hotel California",a:"Eagles",y:1976,g:true},
{t:"Dancing Queen",a:"ABBA",y:1976,g:true},
{t:"Waterloo",a:"ABBA",y:1974,g:true},
{t:"Stayin' Alive",a:"Bee Gees",y:1977,g:true},
{t:"I Will Survive",a:"Gloria Gaynor",y:1978,g:false},
{t:"Y.M.C.A.",a:"Village People",y:1978,g:true},
{t:"No Woman No Cry",a:"Bob Marley and the Wailers",y:1974,g:true},
{t:"Imagine",a:"John Lennon",y:1971,g:false},
{t:"Sweet Home Alabama",a:"Lynyrd Skynyrd",y:1974,g:true},
{t:"September",a:"Earth, Wind & Fire",y:1978,g:true},
{t:"Le Freak",a:"Chic",y:1978,g:true},
{t:"Anarchy in the U.K.",a:"Sex Pistols",y:1976,g:true},
{t:"Resistiré",a:"Duo Dinámico",y:1988,g:true},
{t:"Borriquito",a:"Peret",y:1972,g:false},
{t:"Libre",a:"Nino Bravo",y:1972,g:false},
{t:"Un Beso y una Flor",a:"Nino Bravo",y:1972,g:false},
{t:"A Mi Manera (My Way)",a:"Julio Iglesias",y:1978,g:false},
{t:"Cuéntame",a:"Ana Belén",y:1972,g:false},
{t:"L'Estaca",a:"Lluís Llach",y:1968,g:false},
{t:"Mediterráneo",a:"Joan Manuel Serrat",y:1971,g:false},
{t:"Solo le Pido a Dios",a:"Mercedes Sosa",y:1969,g:false},
{t:"Mi Gran Noche",a:"Raphael",y:1967,g:false},

// ============ 1980-1989 ============
{t:"Billie Jean",a:"Michael Jackson",y:1983,g:false},
{t:"Beat It",a:"Michael Jackson",y:1983,g:false},
{t:"Thriller",a:"Michael Jackson",y:1982,g:false},
{t:"Another One Bites the Dust",a:"Queen",y:1980,g:true},
{t:"Don't Stop Believin'",a:"Journey",y:1981,g:true},
{t:"Every Breath You Take",a:"The Police",y:1983,g:true},
{t:"Sweet Dreams (Are Made of This)",a:"Eurythmics",y:1983,g:true},
{t:"Africa",a:"Toto",y:1982,g:true},
{t:"Karma Chameleon",a:"Culture Club",y:1983,g:true},
{t:"Girls Just Want to Have Fun",a:"Cyndi Lauper",y:1983,g:false},
{t:"Total Eclipse of the Heart",a:"Bonnie Tyler",y:1983,g:false},
{t:"Let's Dance",a:"David Bowie",y:1983,g:false},
{t:"When Doves Cry",a:"Prince",y:1984,g:false},
{t:"Like a Virgin",a:"Madonna",y:1984,g:false},
{t:"Purple Rain",a:"Prince",y:1984,g:false},
{t:"Wake Me Up Before You Go-Go",a:"Wham!",y:1984,g:true},
{t:"Take On Me",a:"a-ha",y:1985,g:true},
{t:"Money for Nothing",a:"Dire Straits",y:1985,g:true},
{t:"We Are the World",a:"USA for Africa",y:1985,g:true},
{t:"Sledgehammer",a:"Peter Gabriel",y:1986,g:false},
{t:"Livin' on a Prayer",a:"Bon Jovi",y:1986,g:true},
{t:"With or Without You",a:"U2",y:1987,g:true},
{t:"I Wanna Dance with Somebody",a:"Whitney Houston",y:1987,g:false},
{t:"Faith",a:"George Michael",y:1987,g:false},
{t:"Sweet Child O' Mine",a:"Guns N' Roses",y:1987,g:true},
{t:"Never Gonna Give You Up",a:"Rick Astley",y:1987,g:false},
{t:"Like a Prayer",a:"Madonna",y:1989,g:false},
{t:"Should I Stay or Should I Go",a:"The Clash",y:1982,g:true},
{t:"Uptown Girl",a:"Billy Joel",y:1983,g:false},
{t:"Jump",a:"Van Halen",y:1984,g:true},
{t:"Rock Me Amadeus",a:"Falco",y:1985,g:false},
{t:"Time After Time",a:"Cyndi Lauper",y:1983,g:false},
{t:"Video Killed the Radio Star",a:"The Buggles",y:1979,g:true},
{t:"Ghostbusters",a:"Ray Parker Jr.",y:1984,g:false},
{t:"Don't You (Forget About Me)",a:"Simple Minds",y:1985,g:true},
{t:"Self Control",a:"Laura Branigan",y:1984,g:false},
{t:"Maniac",a:"Michael Sembello",y:1983,g:false},
{t:"Flashdance... What a Feeling",a:"Irene Cara",y:1983,g:false},
{t:"Blue Monday",a:"New Order",y:1983,g:true},
{t:"Enola Gay",a:"OMD",y:1980,g:true},
{t:"Alone",a:"Heart",y:1987,g:true},
{t:"Kiss",a:"Prince",y:1986,g:false},
{t:"Big in Japan",a:"Alphaville",y:1984,g:true},
{t:"Forever Young",a:"Alphaville",y:1984,g:true},
{t:"La Isla Bonita",a:"Madonna",y:1986,g:false},
{t:"Everybody Wants to Rule the World",a:"Tears for Fears",y:1985,g:true},
{t:"Hungry Like the Wolf",a:"Duran Duran",y:1982,g:true},
// --- Pop español 80s ---
{t:"Hijo de la Luna",a:"Mecano",y:1986,g:true},
{t:"Mujer Contra Mujer",a:"Mecano",y:1988,g:true},
{t:"Me Colé en una Fiesta",a:"Mecano",y:1982,g:true},
{t:"Un Año Más",a:"Mecano",y:1988,g:true},
{t:"Devuélveme a Mi Chica",a:"Hombres G",y:1985,g:true},
{t:"Sufre Mamón",a:"Hombres G",y:1985,g:true},
{t:"Marta Tiene un Marcapasos",a:"Hombres G",y:1988,g:true},
{t:"A Contraluz",a:"Duncan Dhu",y:1985,g:true},
{t:"Bailando",a:"Alaska y Dinarama",y:1985,g:true},
{t:"A Quién le Importa",a:"Alaska y Dinarama",y:1986,g:true},
{t:"Enloquéceme",a:"Alaska y Dinarama",y:1983,g:true},
{t:"Escuela de Calor",a:"Radio Futura",y:1980,g:true},
{t:"La Estatua del Jardín Botánico",a:"Radio Futura",y:1987,g:true},
{t:"Chica de Ayer",a:"Nacha Pop",y:1980,g:true},
{t:"Aquellos Años Locos",a:"Gabinete Caligari",y:1986,g:true},
{t:"Y Nos Dieron las Diez",a:"Joaquín Sabina",y:1980,g:false},
// --- Italia 80s ---
{t:"Sarà Perché Ti Amo",a:"Ricchi e Poveri",y:1981,g:true},
{t:"Se M'innamoro",a:"Ricchi e Poveri",y:1981,g:true},
{t:"L'Italiano",a:"Toto Cutugno",y:1983,g:false},
{t:"Felicità",a:"Al Bano y Romina Power",y:1982,g:false},

// ============ 1990-1999 ============
{t:"Vogue",a:"Madonna",y:1990,g:false},
{t:"Losing My Religion",a:"R.E.M.",y:1991,g:true},
{t:"Smells Like Teen Spirit",a:"Nirvana",y:1991,g:true},
{t:"Nothing Else Matters",a:"Metallica",y:1991,g:true},
{t:"I Will Always Love You",a:"Whitney Houston",y:1992,g:false},
{t:"Creep",a:"Radiohead",y:1992,g:true},
{t:"What's Up?",a:"4 Non Blondes",y:1993,g:true},
{t:"All That She Wants",a:"Ace of Base",y:1993,g:true},
{t:"Zombie",a:"The Cranberries",y:1994,g:true},
{t:"Gangsta's Paradise",a:"Coolio",y:1995,g:false},
{t:"Wonderwall",a:"Oasis",y:1995,g:true},
{t:"Livin' la Vida Loca",a:"Ricky Martin",y:1999,g:false},
{t:"La Copa de la Vida",a:"Ricky Martin",y:1998,g:false},
{t:"Wannabe",a:"Spice Girls",y:1996,g:true},
{t:"...Baby One More Time",a:"Britney Spears",y:1998,g:false},
{t:"My Heart Will Go On",a:"Céline Dion",y:1997,g:false},
{t:"Believe",a:"Cher",y:1998,g:false},
{t:"Bailamos",a:"Enrique Iglesias",y:1999,g:false},
{t:"Sex Bomb",a:"Tom Jones",y:1999,g:false},
{t:"I Want It That Way",a:"Backstreet Boys",y:1999,g:true},
{t:"Macarena",a:"Los Del Rio",y:1996,g:true},
{t:"Barbie Girl",a:"Aqua",y:1997,g:true},
{t:"Torn",a:"Natalie Imbruglia",y:1997,g:false},
{t:"Kiss Me",a:"Sixpence None the Richer",y:1997,g:true},
{t:"Song 2",a:"Blur",y:1997,g:true},
{t:"Cotton Eye Joe",a:"Rednex",y:1994,g:true},
{t:"Rhythm Is a Dancer",a:"Snap!",y:1992,g:true},
{t:"Mambo No. 5",a:"Lou Bega",y:1999,g:false},
{t:"Blue (Da Ba Dee)",a:"Eiffel 65",y:1999,g:true},
{t:"Freed from Desire",a:"Gala",y:1996,g:false},
{t:"No Diggity",a:"Blackstreet",y:1996,g:true},
{t:"Killing Me Softly",a:"Fugees",y:1996,g:true},
{t:"Waterfalls",a:"TLC",y:1995,g:true},
{t:"Don't Speak",a:"No Doubt",y:1996,g:true},
{t:"Angels",a:"Robbie Williams",y:1997,g:false},
{t:"Let Me Entertain You",a:"Robbie Williams",y:1997,g:false},
{t:"Tubthumping",a:"Chumbawamba",y:1997,g:true},
{t:"MMMBop",a:"Hanson",y:1997,g:true},
{t:"Ray of Light",a:"Madonna",y:1998,g:false},
{t:"All Star",a:"Smash Mouth",y:1999,g:true},
{t:"Genie in a Bottle",a:"Christina Aguilera",y:1999,g:false},
{t:"Rosas",a:"La Oreja de Van Gogh",y:1998,g:true},
{t:"Puedes Contar Conmigo",a:"La Oreja de Van Gogh",y:1998,g:true},
{t:"Corazón Partío",a:"Alejandro Sanz",y:1997,g:false},
{t:"Y, ¿Si Fuera Ella?",a:"Alejandro Sanz",y:1998,g:false},
{t:"Amiga Mía",a:"Alejandro Sanz",y:1991,g:false},
{t:"Sobreviviré",a:"Mónica Naranjo",y:1997,g:false},
{t:"Solo se Vive una Vez",a:"Azúcar Moreno",y:1990,g:true},
{t:"Bandido",a:"Azúcar Moreno",y:1988,g:true},
{t:"El Muerto Vivo",a:"Estopa",y:1999,g:true},
{t:"Como Camarón",a:"Estopa",y:1999,g:true},
// --- Italia 90s ---
{t:"Con Te Partirò",a:"Andrea Bocelli",y:1995,g:false},
{t:"Se Bastasse una Canzone",a:"Eros Ramazzotti",y:1990,g:false},
{t:"Cose della Vita",a:"Eros Ramazzotti",y:1993,g:false},
{t:"Un'Emozione per Sempre",a:"Eros Ramazzotti",y:1996,g:false},

// ============ 2000-2009 ============
{t:"Hey Ya!",a:"OutKast",y:2003,g:true},
{t:"Crazy in Love",a:"Beyoncé ft. Jay-Z",y:2003,g:false},
{t:"Toxic",a:"Britney Spears",y:2003,g:false},
{t:"Since U Been Gone",a:"Kelly Clarkson",y:2004,g:false},
{t:"Hips Don't Lie",a:"Shakira",y:2006,g:false},
{t:"Umbrella",a:"Rihanna",y:2007,g:false},
{t:"Rehab",a:"Amy Winehouse",y:2006,g:false},
{t:"Mr. Brightside",a:"The Killers",y:2004,g:true},
{t:"Seven Nation Army",a:"The White Stripes",y:2003,g:true},
{t:"Clocks",a:"Coldplay",y:2002,g:true},
{t:"Beautiful Day",a:"U2",y:2000,g:true},
{t:"Complicated",a:"Avril Lavigne",y:2002,g:false},
{t:"Just Dance",a:"Lady Gaga",y:2008,g:false},
{t:"Poker Face",a:"Lady Gaga",y:2008,g:false},
{t:"Single Ladies",a:"Beyoncé",y:2008,g:false},
{t:"Viva la Vida",a:"Coldplay",y:2008,g:true},
{t:"I Gotta Feeling",a:"The Black Eyed Peas",y:2009,g:true},
{t:"Bad Romance",a:"Lady Gaga",y:2009,g:false},
{t:"TiK ToK",a:"Kesha",y:2009,g:false},
{t:"SexyBack",a:"Justin Timberlake",y:2006,g:false},
{t:"Don't Cha",a:"The Pussycat Dolls",y:2005,g:true},
{t:"It Wasn't Me",a:"Shaggy",y:2000,g:false},
{t:"Can't Get You Out of My Head",a:"Kylie Minogue",y:2001,g:false},
{t:"Feel Good Inc.",a:"Gorillaz",y:2005,g:true},
{t:"Chasing Cars",a:"Snow Patrol",y:2006,g:true},
{t:"Gold Digger",a:"Kanye West ft. Jamie Foxx",y:2005,g:false},
{t:"American Idiot",a:"Green Day",y:2004,g:true},
{t:"Dani California",a:"Red Hot Chili Peppers",y:2006,g:true},
{t:"Crazy",a:"Gnarls Barkley",y:2006,g:true},
{t:"Gasolina",a:"Daddy Yankee",y:2004,g:false},
{t:"La Tortura",a:"Shakira ft. Alejandro Sanz",y:2005,g:false},
{t:"La Camisa Negra",a:"Juanes",y:2004,g:false},
{t:"A Dios le Pido",a:"Juanes",y:2002,g:false},
{t:"In the End",a:"Linkin Park",y:2000,g:true},
{t:"Numb",a:"Linkin Park",y:2003,g:true},
{t:"Bring Me to Life",a:"Evanescence",y:2003,g:true},
{t:"Antes Muerta que Sencilla",a:"Amaral",y:2002,g:true},
{t:"Sin Ti No Soy Nada",a:"Amaral",y:2002,g:true},
{t:"Moriría por Vos",a:"Amaral",y:2005,g:true},
{t:"El Universo Sobre Mí",a:"Amaral",y:2005,g:true},
{t:"19 Días y 500 Noches",a:"Joaquín Sabina",y:1999,g:false},
{t:"Peligro",a:"David Bisbal",y:2002,g:false},
{t:"Ave María",a:"David Bisbal",y:2002,g:false},
{t:"Bulería",a:"David Bisbal",y:2002,g:false},
{t:"Escondidos",a:"David Bisbal",y:2004,g:false},
{t:"Dime",a:"David Bisbal",y:2002,g:false},
{t:"Colgando en Tus Manos",a:"Carlos Baute ft. Marta Sánchez",y:2008,g:false},
{t:"Cuando Zarpa el Amor",a:"Camela",y:1997,g:true},
{t:"No Puedo Vivir Sin Ti",a:"Camela",y:1994,g:true},
{t:"Ella No Sabe",a:"Sergio Dalma",y:1994,g:false},
{t:"La Flaca",a:"Jarabe de Palo",y:1996,g:true},
{t:"Depende",a:"Jarabe de Palo",y:1998,g:true},
{t:"Héroe",a:"Enrique Iglesias",y:2001,g:false},
{t:"Palmeras en el Jardín",a:"Nena Daconte",y:2007,g:true},
{t:"El Baile del Sapo",a:"Melody",y:2001,g:false},
{t:"Se Me Olvidó Otra Vez",a:"Melendi",y:2008,g:false},
{t:"Caminando por la Vida",a:"Melendi",y:2007,g:false},
{t:"La Playa",a:"El Canto del Loco",y:2005,g:true},
{t:"Zapatillas",a:"El Canto del Loco",y:2002,g:true},
{t:"Peter Pan",a:"El Canto del Loco",y:2002,g:true},
{t:"Bulevar",a:"Vetusta Morla",y:2008,g:true},
{t:"La Playa",a:"Malú",y:2003,g:false},
{t:"Aprendiz",a:"Malú",y:2000,g:false},
// --- K-pop / global temprano ---
{t:"Gangnam Style",a:"Psy",y:2012,g:false},

// ============ 2010-2019 ============
{t:"Rolling in the Deep",a:"Adele",y:2010,g:false},
{t:"Someone Like You",a:"Adele",y:2011,g:false},
{t:"Hello",a:"Adele",y:2015,g:false},
{t:"Party Rock Anthem",a:"LMFAO",y:2011,g:true},
{t:"Moves Like Jagger",a:"Maroon 5",y:2011,g:true},
{t:"Somebody That I Used to Know",a:"Gotye",y:2011,g:false},
{t:"Call Me Maybe",a:"Carly Rae Jepsen",y:2012,g:false},
{t:"Blurred Lines",a:"Robin Thicke",y:2013,g:false},
{t:"Get Lucky",a:"Daft Punk ft. Pharrell Williams",y:2013,g:true},
{t:"Royals",a:"Lorde",y:2013,g:false},
{t:"Wrecking Ball",a:"Miley Cyrus",y:2013,g:false},
{t:"Happy",a:"Pharrell Williams",y:2013,g:false},
{t:"Roar",a:"Katy Perry",y:2013,g:false},
{t:"Counting Stars",a:"OneRepublic",y:2013,g:true},
{t:"All of Me",a:"John Legend",y:2013,g:false},
{t:"Shake It Off",a:"Taylor Swift",y:2014,g:false},
{t:"Uptown Funk",a:"Mark Ronson ft. Bruno Mars",y:2014,g:false},
{t:"Thinking Out Loud",a:"Ed Sheeran",y:2014,g:false},
{t:"Take Me to Church",a:"Hozier",y:2013,g:false},
{t:"Chandelier",a:"Sia",y:2014,g:false},
{t:"Sorry",a:"Justin Bieber",y:2015,g:false},
{t:"Can't Feel My Face",a:"The Weeknd",y:2015,g:false},
{t:"Shape of You",a:"Ed Sheeran",y:2017,g:false},
{t:"Despacito",a:"Luis Fonsi ft. Daddy Yankee",y:2017,g:false},
{t:"One Dance",a:"Drake",y:2016,g:false},
{t:"Closer",a:"The Chainsmokers ft. Halsey",y:2016,g:true},
{t:"Cheap Thrills",a:"Sia",y:2016,g:false},
{t:"7 Rings",a:"Ariana Grande",y:2019,g:false},
{t:"God's Plan",a:"Drake",y:2018,g:false},
{t:"Havana",a:"Camila Cabello",y:2017,g:false},
{t:"Perfect",a:"Ed Sheeran",y:2017,g:false},
{t:"Old Town Road",a:"Lil Nas X",y:2019,g:false},
{t:"Bad Guy",a:"Billie Eilish",y:2019,g:false},
{t:"Someone You Loved",a:"Lewis Capaldi",y:2019,g:false},
{t:"Señorita",a:"Shawn Mendes & Camila Cabello",y:2019,g:false},
{t:"Sunflower",a:"Post Malone & Swae Lee",y:2018,g:false},
{t:"Thank U, Next",a:"Ariana Grande",y:2018,g:false},
{t:"Radioactive",a:"Imagine Dragons",y:2012,g:true},
{t:"Thrift Shop",a:"Macklemore & Ryan Lewis",y:2012,g:false},
{t:"Locked Out of Heaven",a:"Bruno Mars",y:2012,g:false},
{t:"Marry You",a:"Bruno Mars",y:2010,g:false},
{t:"Sugar",a:"Maroon 5",y:2015,g:true},
{t:"Girls Like You",a:"Maroon 5",y:2018,g:true},
{t:"Formation",a:"Beyoncé",y:2016,g:false},
{t:"Work",a:"Rihanna ft. Drake",y:2016,g:false},
{t:"Love Yourself",a:"Justin Bieber",y:2015,g:false},
{t:"Stressed Out",a:"Twenty One Pilots",y:2015,g:true},
{t:"Photograph",a:"Ed Sheeran",y:2014,g:false},
{t:"Rockstar",a:"Post Malone ft. 21 Savage",y:2017,g:false},
{t:"Humble",a:"Kendrick Lamar",y:2017,g:false},
{t:"Mi Gente",a:"J Balvin & Willy William",y:2017,g:false},
{t:"Vente Pa' Ca",a:"Ricky Martin ft. Maluma",y:2016,g:false},
{t:"Danza Kuduro",a:"Don Omar ft. Lucenzo",y:2010,g:false},
{t:"Vivir Mi Vida",a:"Marc Anthony",y:2013,g:false},
{t:"Wake Me Up",a:"Avicii",y:2013,g:false},
{t:"Titanium",a:"David Guetta ft. Sia",y:2011,g:false},
{t:"Animals",a:"Martin Garrix",y:2013,g:false},
{t:"Lean On",a:"Major Lazer & DJ Snake",y:2015,g:true},
{t:"This Is What You Came For",a:"Calvin Harris ft. Rihanna",y:2016,g:false},
{t:"Faded",a:"Alan Walker",y:2015,g:false},
{t:"New Rules",a:"Dua Lipa",y:2017,g:false},
{t:"IDGAF",a:"Dua Lipa",y:2018,g:false},
{t:"Shallow",a:"Lady Gaga & Bradley Cooper",y:2018,g:false},
{t:"Truth Hurts",a:"Lizzo",y:2019,g:false},
{t:"Blank Space",a:"Taylor Swift",y:2014,g:false},
{t:"Bang Bang",a:"Jessie J, Ariana Grande, Nicki Minaj",y:2014,g:false},
{t:"Waka Waka (This Time for Africa)",a:"Shakira",y:2010,g:false},
{t:"Loca",a:"Shakira ft. El Cata",y:2010,g:false},
{t:"Antes de Ti",a:"Pablo Alborán",y:2011,g:false},
{t:"Solamente Tú",a:"Pablo Alborán",y:2010,g:false},
{t:"Vivir Sin Aire",a:"Pablo Alborán",y:2013,g:false},
{t:"Se Me Olvidó Otra Vez",a:"Melendi",y:2008,g:false},
{t:"Con la Luna Llena",a:"Melendi",y:2007,g:false},
{t:"Copenhague",a:"Vetusta Morla",y:2011,g:true},
{t:"Lo Malo",a:"Aitana y Ana Guerra",y:2018,g:false},
{t:"Vas a Quedarte",a:"Manuel Carrasco",y:2010,g:false},
{t:"Que Nadie",a:"Manuel Carrasco",y:2016,g:false},
{t:"Vino Tinto",a:"Estopa",y:2003,g:true},
{t:"Corazones",a:"Fangoria",y:2008,g:true},
{t:"Retorciendo Palabras",a:"Fangoria",y:2004,g:true},
{t:"Camino Soleado",a:"Fito & Fitipaldis",y:2013,g:true},
{t:"Soldadito Marinero",a:"Fito & Fitipaldis",y:2005,g:true},
{t:"Escápate Conmigo",a:"Wisin ft. Ozuna",y:2017,g:false},
{t:"Grande Amore",a:"Il Volo",y:2015,g:true},
{t:"Sincerità",a:"Fred De Palma ft. Ana Mena",y:2019,g:false},
{t:"DNA",a:"BTS",y:2017,g:true},
{t:"Boy With Luv",a:"BTS ft. Halsey",y:2019,g:true},
{t:"DDU-DU DDU-DU",a:"BLACKPINK",y:2018,g:true},
{t:"Kill This Love",a:"BLACKPINK",y:2019,g:true},

// ============ 2020-2026 ============
{t:"Blinding Lights",a:"The Weeknd",y:2019,g:false},
{t:"Dance Monkey",a:"Tones and I",y:2019,g:false},
{t:"Watermelon Sugar",a:"Harry Styles",y:2019,g:false},
{t:"Levitating",a:"Dua Lipa",y:2020,g:false},
{t:"Save Your Tears",a:"The Weeknd",y:2020,g:false},
{t:"Drivers License",a:"Olivia Rodrigo",y:2021,g:false},
{t:"Good 4 U",a:"Olivia Rodrigo",y:2021,g:false},
{t:"Stay",a:"The Kid LAROI & Justin Bieber",y:2021,g:false},
{t:"Peaches",a:"Justin Bieber",y:2021,g:false},
{t:"Montero (Call Me by Your Name)",a:"Lil Nas X",y:2021,g:false},
{t:"Industry Baby",a:"Lil Nas X & Jack Harlow",y:2021,g:false},
{t:"As It Was",a:"Harry Styles",y:2022,g:false},
{t:"About Damn Time",a:"Lizzo",y:2022,g:false},
{t:"Anti-Hero",a:"Taylor Swift",y:2022,g:false},
{t:"Flowers",a:"Miley Cyrus",y:2023,g:false},
{t:"Calm Down",a:"Rema & Selena Gomez",y:2022,g:false},
{t:"Unholy",a:"Sam Smith & Kim Petras",y:2022,g:false},
{t:"Vampire",a:"Olivia Rodrigo",y:2023,g:false},
{t:"Cruel Summer",a:"Taylor Swift",y:2019,g:false},
{t:"Espresso",a:"Sabrina Carpenter",y:2024,g:false},
{t:"Please Please Please",a:"Sabrina Carpenter",y:2024,g:false},
{t:"Die With a Smile",a:"Lady Gaga & Bruno Mars",y:2024,g:false},
{t:"Texas Hold 'Em",a:"Beyoncé",y:2024,g:false},
{t:"Not Like Us",a:"Kendrick Lamar",y:2024,g:false},
{t:"Ordinary",a:"Alex Warren",y:2025,g:false},
{t:"Apt.",a:"Rosé & Bruno Mars",y:2024,g:false},
{t:"TQG",a:"Karol G & Shakira",y:2023,g:false},
{t:"Ella Baila Sola",a:"Eslabón Armado & Peso Pluma",y:2023,g:true},
{t:"Quevedo: Bzrp Music Sessions, Vol. 52",a:"Bizarrap & Quevedo",y:2022,g:false},
{t:"Provenza",a:"Karol G",y:2022,g:false},
{t:"Pepas",a:"Farruko",y:2021,g:false},
{t:"Todo de Ti",a:"Rauw Alejandro",y:2021,g:false},
{t:"Tacones Rojos",a:"Sebastián Yatra",y:2022,g:false},
{t:"Mamiii",a:"Becky G y Karol G",y:2022,g:false},
{t:"Cayó la Noche (Remix)",a:"La Pantera, Quevedo, Juseph",y:2022,g:false},
{t:"Ay Mamá",a:"Rigoberta Bandini",y:2022,g:false},
{t:"Música Ligera",a:"Ana Mena",y:2022,g:false},
{t:"SloMo",a:"Chanel",y:2022,g:false},
{t:"Despechá",a:"Rosalía",y:2022,g:false},
{t:"Candy",a:"Rosalía",y:2022,g:false},
{t:"Con Altura",a:"Rosalía ft. J Balvin",y:2019,g:false},
{t:"Malamente",a:"Rosalía",y:2018,g:false},
{t:"Bizcochito",a:"Rosalía",y:2019,g:false},
{t:"Saoko",a:"Rosalía",y:2022,g:false},
{t:"Felices los 4",a:"Maluma",y:2017,g:false},
{t:"La Plena (W Sound 05)",a:"W Sound, Beéle y Ovy on the Drums",y:2025,g:false},
{t:"Droga",a:"Mora y C. Tangana",y:2025,g:false},
{t:"Si Antes Te Hubiera Conocido",a:"Karol G",y:2024,g:false},
{t:"Gran Vía",a:"Quevedo y Aitana",y:2025,g:false},
{t:"Me Has Invitado a Bailar",a:"Dani Fernández",y:2025,g:false},
{t:"6 de Febrero",a:"Aitana",y:2025,g:false},
{t:"Nuevayol",a:"Bad Bunny",y:2025,g:false},
{t:"Café con Ron",a:"Bad Bunny",y:2025,g:false},
{t:"Turista",a:"Bad Bunny",y:2022,g:false},
{t:"Titi Me Preguntó",a:"Bad Bunny",y:2022,g:false},
{t:"Moscow Mule",a:"Bad Bunny",y:2022,g:false},
{t:"Se Pone las Nike",a:"Cano",y:2025,g:false},
{t:"Soleao",a:"Myke Towers ft. Quevedo",y:2025,g:false},
{t:"Blackout",a:"Emilia, TINI y Nicki Nicole",y:2025,g:false},
{t:"Da Me",a:"Bad Gyal",y:2025,g:false},
{t:"Duro y Dulce",a:"Lola Índigo",y:2022,g:false},
{t:"Discoteka",a:"Lola Índigo",y:2023,g:false},
{t:"Terral",a:"Vetusta Morla",y:2021,g:true},
{t:"Que Vuelvas",a:"Carin León & Grupo Frontera",y:2022,g:true},
{t:"Ni Bien Ni Mal",a:"Bad Gyal",y:2022,g:false},
{t:"Yonaguni",a:"Bad Bunny",y:2021,g:false},
{t:"Dákiti",a:"Bad Bunny & Jhay Cortez",y:2020,g:false},
{t:"La Noche de Anoche",a:"Bad Bunny & Rosalía",y:2020,g:false},
{t:"Relación",a:"Sech ft. Daddy Yankee, J Balvin, Rosalía, Farruko",y:2019,g:false},
{t:"Cupid",a:"FIFTY FIFTY",y:2023,g:true},
{t:"Ditto",a:"NewJeans",y:2022,g:true},
{t:"How Sweet",a:"NewJeans",y:2024,g:true},
{t:"Shut Down",a:"BLACKPINK",y:2022,g:true},
{t:"Butter",a:"BTS",y:2021,g:true},
];
